# Generated by Django 4.0.3 on 2024-03-30 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomas_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
