# Generated by Django 4.0.3 on 2024-09-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
