# Generated by Django 4.0.3 on 2024-08-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edu_core.activity'),
        ),
    ]
