# Generated by Django 4.0.3 on 2024-09-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0002_alter_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_blocks/'),
        ),
    ]
