# Generated by Django 4.0.3 on 2024-03-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0002_diploma_issued_by_alter_diploma_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='student',
        ),
        migrations.AddField(
            model_name='diploma',
            name='student_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
