# Generated by Django 4.0.3 on 2024-08-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0002_alter_question_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='questions',
            field=models.ManyToManyField(related_name='activity_set', through='edu_core.ActivityQuestion', to='edu_core.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_questions', to='edu_core.activity'),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_questions', to='edu_core.course'),
        ),
        migrations.AddField(
            model_name='activityquestion',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_core.activity'),
        ),
        migrations.AddField(
            model_name='activityquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_core.question'),
        ),
        migrations.AlterUniqueTogether(
            name='activityquestion',
            unique_together={('activity', 'question')},
        ),
    ]
