# Generated by Django 4.0.3 on 2024-09-12 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0003_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='yt_video_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
