# Generated by Django 4.0.3 on 2024-08-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0003_activityquestion_activity_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityquestion',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
    ]
