# Generated by Django 4.0.3 on 2024-09-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0004_question_yt_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='content_block_files/'),
        ),
    ]
