# Generated by Django 4.0.3 on 2024-08-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0004_activityquestion_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityquestion',
            name='is_separator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activityquestion',
            name='page_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activityquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_core.question'),
        ),
    ]
