# Generated by Django 4.0.3 on 2024-04-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0005_activity_course_registration_lesson_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
