# Generated by Django 4.0.3 on 2024-09-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0005_question_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='content_block_audio/'),
        ),
    ]
