# Generated by Django 4.0.3 on 2024-08-27 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0005_activityquestion_is_separator_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityquestion',
            unique_together={('activity', 'order')},
        ),
    ]
