# Generated by Django 4.0.3 on 2024-04-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0006_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='structured_content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True or False')], max_length=50),
        ),
    ]
