# Generated by Django 4.0.3 on 2024-09-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0006_question_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='audio_file',
        ),
    ]
