# Generated by Django 4.0.3 on 2024-08-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0006_alter_activityquestion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityquestion',
            name='temp_order',
            field=models.IntegerField(default=0),
        ),
    ]
