# Generated by Django 4.0.3 on 2024-10-06 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0007_remove_question_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_corpus/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpus', to='edu_core.course')),
            ],
        ),
    ]
