# Generated by Django 4.0.3 on 2024-08-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0008_remove_activityquestion_temp_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
