# Generated by Django 4.0.3 on 2024-10-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0009_question_feedback_question_feedback_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='feedback_visibility',
        ),
        migrations.AddField(
            model_name='activity',
            name='feedback_visibility',
            field=models.CharField(choices=[('never', 'Never'), ('during', 'During Assessment'), ('end', 'End of Assessment')], default='never', help_text='Choose when to show feedback for all questions in this activity.', max_length=10),
        ),
    ]
