# Generated by Django 4.0.3 on 2024-10-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0010_remove_question_feedback_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='feedback_visibility',
            field=models.CharField(choices=[('never', 'Never'), ('during', 'During Assessment'), ('end', 'End of Assessment'), ('always', 'Always')], default='never', help_text='Choose when to show feedback for all questions in this activity.', max_length=10),
        ),
    ]
