# Generated by Django 4.0.3 on 2024-10-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0012_activity_max_attempts_activity_unlimited_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='max_attempts',
        ),
        migrations.AddField(
            model_name='activity',
            name='maximum_attempts',
            field=models.PositiveIntegerField(default=1, help_text='Set the maximum number of attempts allowed.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='unlimited_attempts',
            field=models.BooleanField(default=False, help_text='Allow unlimited attempts if checked.'),
        ),
    ]
