# Generated by Django 4.0.3 on 2024-10-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0013_remove_activity_max_attempts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='maximum_attempts',
            new_name='max_attempts',
        ),
    ]
