# Generated by Django 4.0.3 on 2024-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0015_alter_activity_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Set the maximum number of attempts allowed.', null=True),
        ),
    ]
